---
- name: install {{kafka_install_parent_dir}}/kafka/config/*.properties
  become: yes
  become_user: root
  with_items:
    - server.properties
    - consumer.properties
    - producer.properties
  template: >-
    src={{item}}.j2
    dest={{kafka_install_parent_dir}}/kafka/config/{{item}}
    mode=0644

- name: install kafka.service...
  become: yes
  become_user: root
  register: kafka_service_installed
  template: >-
    src=kafka.service.j2
    dest=/etc/systemd/system/kafka.service
    mode=0644

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: kafka_service_installed|changed and kafka_launch
  command: systemctl daemon-reload

- name: launch kafka...
  become: yes
  become_user: root
  when: kafka_launch
  service: name=kafka enabled=yes state=started
  
