---
- name: download kafka tgz...
  get_url: >
   url={{kafka_tgz_url}}
   dest=/tmp/{{kafka_tgz}}
   owner=root
   group=root
   mode=0644

- name: unarchive...
  unarchive: >
    copy=no
    src=/tmp/{{kafka_tgz}}
    dest=/opt

- name: link...
  file: >-
    src=/opt/kafka_{{kafka_scala_ver}}-{{kafka_ver}}
    dest=/opt/kafka
    state=link

- name: include kafka in the default path
  template: >
    src='etc/profile.d/kafka.sh'
    dest='/etc/profile.d/kafka.sh'
    mode=644
    owner=root
    group=root

- name: install /opt/kafka/config/server.properties
  template: >-
    src={{item}}.j2
    dest=/opt/kafka/config/{{item}}
    owner=root
    group=root
    mode=0644
  with_items:
    - server.properties
    - consumer.properties
    - producer.properties

- name: install kafka.service...
  register: kafka_service_installed
  template: >-
    src=kafka.service.j2
    dest=/etc/systemd/system/kafka.service
    owner=root
    group=root
    mode=0644

- name: systemctl daemon-reload
  when: kafka_service_installed.changed
  command: systemctl daemon-reload

- name: launch kafka...
  service: name=kafka.service enabled=yes state=started
  
